version: '2'

services: 
      protos:
        build: 
            context: .
            dockerfile: Dockerfile.protos
        entrypoint: ash compile_protos.sh 
        volumes:
            - ./sgproto:/data/sgproto
